version: '3.8'

services:
  php-env:
    image: php:8.0-apache
    ports:
      - 3000:80
    volumes:
      - C:/www/src:/var/www/html
    networks:
      - entorno-web
    depends_on:
      - mysql
    
  
  mysql:
    image: mysql
    container_name: bbdd
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - entorno-web
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - entorno-web
    
networks:
  entorno-web:
  
volumes:
  mysql_data:

    

